version: "3.7"

services:
  streamonitor:
    build: ./
    image: sm:latest
    volumes:
      - ./downloads:/app/downloads
      - ./config.json:/app/config.json
      - ./parameters.py:/app/parameters.py
#    ports:
#      - '6969:6969'

networks:
  default:
    external: true
    name: npm
